# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: lineups.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Lineup(betterproto.Message):
    players_id: List[int] = betterproto.int64_field(1)


@dataclass
class LineupTeam(betterproto.Message):
    last_starting_11: "Lineup" = betterproto.message_field(1)
    team_name: str = betterproto.string_field(2)


@dataclass
class LineupList(betterproto.Message):
    teams: List["LineupTeam"] = betterproto.message_field(1)
