# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: player.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class Game(betterproto.Message):
    game_id: float = betterproto.float_field(1)
    game_date: str = betterproto.string_field(2)
    xg: float = betterproto.float_field(3)
    xt_all: float = betterproto.float_field(4)
    xt_only_pos: float = betterproto.float_field(8)
    xd_press: float = betterproto.float_field(5)
    xd_def: float = betterproto.float_field(6)
    xk_save: float = betterproto.float_field(7)
    xg_against: float = betterproto.float_field(9)
    xt_against_all: float = betterproto.float_field(10)
    xt_against_only_pos: float = betterproto.float_field(32)
    gi: float = betterproto.float_field(11)
    starter: bool = betterproto.bool_field(12)
    team: int = betterproto.int32_field(13)
    home: bool = betterproto.bool_field(14)
    minutes_played: int = betterproto.int32_field(15)
    team_elo: float = betterproto.float_field(16)
    opposition_elo: float = betterproto.float_field(17)
    league_elo: float = betterproto.float_field(18)
    top_league_elo: float = betterproto.float_field(19)
    team_pos: int = betterproto.int32_field(20)
    opp_position: int = betterproto.int32_field(21)
    team_pos_home_away: int = betterproto.int32_field(22)
    opp_position_home_away: int = betterproto.int32_field(23)
    team_form_for: int = betterproto.int32_field(24)
    team_form_against: int = betterproto.int32_field(25)
    opp_form_for: int = betterproto.int32_field(26)
    opp_form_against: int = betterproto.int32_field(27)
    team_form_home_away_for: int = betterproto.int32_field(28)
    team_form_home_away_against: int = betterproto.int32_field(29)
    opp_form_home_away_for: int = betterproto.int32_field(30)
    opp_form_home_away_against: int = betterproto.int32_field(31)


@dataclass
class Player(betterproto.Message):
    player_id: int = betterproto.int32_field(1)
    player_name: str = betterproto.string_field(2)
    expected_game_impact: List["Game"] = betterproto.message_field(3)
