# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: table.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class TableTeam(betterproto.Message):
    team_id: float = betterproto.float_field(1)
    team_name: str = betterproto.string_field(2)
    num_games: int = betterproto.int32_field(3)
    points: int = betterproto.int32_field(4)
    points_home: int = betterproto.int32_field(5)
    points_away: int = betterproto.int32_field(6)
    form_goals_for: List[int] = betterproto.int32_field(7)
    form_goals_for_home: List[int] = betterproto.int32_field(8)
    form_goals_for_away: List[int] = betterproto.int32_field(9)
    form_goals_against: List[int] = betterproto.int32_field(10)
    form_goals_against_home: List[int] = betterproto.int32_field(11)
    form_goals_against_away: List[int] = betterproto.int32_field(12)


@dataclass
class TableCompetition(betterproto.Message):
    table_teams: List["TableTeam"] = betterproto.message_field(1)
    competition: str = betterproto.string_field(2)


@dataclass
class TableList(betterproto.Message):
    tables: List["TableCompetition"] = betterproto.message_field(1)
